name: universal_ble_example
description: Demonstrates how to use the universal_ble plugin.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.1
  expandable: ^5.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  universal_ble:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
