name: universal_ble_example
description: Demonstrates how to use the universal_ble plugin.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.1
  yaml: ^3.1.3
  universal_ble:
    path: ../
  device_preview: ^1.3.1
  device_preview_screenshot: ^1.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  package_rename: ^1.10.1
  flutter_launcher_icons:
    git:
      url: https://github.com/Navideck/flutter_launcher_icons.git
      ref: improve-windows-ico-generation

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/company_identifiers.yaml
