name: universal_ble_example
description: Demonstrates how to use the universal_ble plugin.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.1
  expandable: ^5.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.4
  package_info: ^2.0.2
  url_launcher: ^6.3.2
  universal_ble:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons:
    git:
      url: https://github.com/Navideck/flutter_launcher_icons.git
      ref: improve-windows-ico-generation

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
